# Generated by Django 4.2.8 on 2024-03-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='instance_name',
        ),
        migrations.AddField(
            model_name='instance',
            name='instance_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instance',
            name='instance_key',
            field=models.CharField(max_length=25),
        ),
    ]
