# Generated by Django 4.2.8 on 2024-03-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0003_alter_log_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='excel_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
