# Generated by Django 4.2.8 on 2024-03-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0004_log_excel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whatsapp_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
