# Generated by Django 4.2.8 on 2024-03-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0008_whatsapp_config_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
