# Generated by Django 4.2.8 on 2024-03-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0009_alter_log_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
