# Generated by Django 4.2.8 on 2024-03-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0013_alter_log_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='phone_number',
            field=models.CharField(default=112222222222, max_length=12),
            preserve_default=False,
        ),
    ]
