# Generated by Django 4.2.8 on 2024-03-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_app', '0014_instance_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
